<Project>

  <!-- ============================================ -->
  <!-- Common Properties for All Projects -->
  <!-- ============================================ -->
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12</LangVersion>
  </PropertyGroup>

  <!-- ============================================ -->
  <!-- Build Configuration -->
  <!-- ============================================ -->
  <PropertyGroup>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <!-- ============================================ -->
  <!-- Assembly Information -->
  <!-- ============================================ -->
  <PropertyGroup>
    <Company></Company>
    <Authors></Authors>
    <Copyright>Copyright © 2026</Copyright>
    <Product>ProG Coder Shop Microservices</Product>
  </PropertyGroup>

</Project>

